### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zspitz** [vchirikov/GoToDnSpy#9]
```
---------------------------
[GoToDnSpy] Error
---------------------------
Some error in GoToDnSpy extensiton.
 Please take screenshot and create issue on github with this error
System.MissingMethodException: Method not found: 'Microsoft.VisualStudio.ProjectSystem.IConfiguredProjectServices Microsoft.VisualStudio.ProjectSystem.ConfiguredProject.get_Services()'.
   at GoToDnSpy.EnvDteExtensions.GetProjectPropertyNetCoreWorkaround(Project project, String name)
   at GoToDnSpy.GoToDnSpy.GetTargetOutputPath(Project project)
   at GoToDnSpy.GoToDnSpy.GetCurrentFileOutputAssembly()
   at GoToDnSpy.GoToDnSpy.GetAssemblyPath(SemanticModel semanticModel, String assemblyDef)
   at GoToDnSpy.GoToDnSpy.MenuItemCallback(Object sender, EventArgs e)
---------------------------
OK   
---------------------------
```

(NB. "extensiton" -> "extension".)

**Comment by zspitz** [comment]
Perhaps because this is in a Shared project?

**Comment by vchirikov** [comment]
Closed by https://github.com/vchirikov/GoToDnSpy/commit/5a4c1592
